In [1]:
import numpy as np
import pandas as pd

np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['feature1','feature2','feature3'])
df1['target'] = 0

df = pd.concat([df, df1], ignore_index=True)

df = df.sample(40)

print(df.head())

df = df.sample(40)
     

    feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1


In [2]:
df.head()

,feature1,feature2,feature3,target
25,0.290746,0.866975,0.982643,0
38,-0.764314,1.566504,1.548788,0
24,0.748855,2.593111,1.170818,0
15,-0.045438,1.040886,-0.094035,1
13,-0.022539,0.013422,0.935945,1


In [3]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.


In [4]:
import plotly.express as px

In [5]:
pip install nbformat

Note: you may need to restart the kernel to use updated packages.


In [6]:
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
                    color=df['target'].astype('str'))

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,color='DarkSlateGrey')),
                              selector=dict(mode='markers'))

fig.show()

<h3>Step 1 -> Applying standard Scaling</h3>

In [7]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

df.iloc[:,:3] = scalar.fit_transform(df.iloc[:,:3])

<h3>Step 2 -> Find Covarience Matrix</h3>

In [17]:


covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


<h3>Step 3 -> Finding EV and EVs</h3>

In [18]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [19]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [20]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])