In [127]:
import pandas as pd
import numpy as np

In [128]:
df = pd.read_csv('train.csv')

In [129]:
df.shape

(891, 12)

In [130]:
df.sample(5)


PassengerId  Survived  Pclass                            Name     Sex  \
448          449         1       3  Baclini, Miss. Marie Catherine  female   
346          347         1       2       Smith, Miss. Marion Elsie  female   
718          719         0       3             McEvoy, Mr. Michael    male   
488          489         0       3   Somerton, Mr. Francis William    male   
790          791         0       3        Keane, Mr. Andrew "Andy"    male   

      Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
448   5.0      2      1        2666  19.2583   NaN        C  
346  40.0      0      0       31418  13.0000   NaN        S  
718   NaN      0      0       36568  15.5000   NaN        Q  
488  30.0      0      0  A.5. 18509   8.0500   NaN        S  
790   NaN      0      0       12460   7.7500   NaN        Q

In [131]:
df.drop(columns=['Ticket'], inplace=True)


In [179]:
df.drop(columns=['Name'], inplace=True)


In [132]:
df.drop(columns=['PassengerId','Cabin'],inplace=True)


In [180]:
df.head(5)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

Inputs

In [134]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

Step 1 train test split

In [135]:
x = df.drop(columns=['Survived'])
y = df['Survived']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [136]:
x_train.shape

(712, 8)

In [154]:
x_train.head()

Pclass                                Name     Sex   Age  SibSp  Parch  \
331       1                 Partner, Mr. Austen    male  45.5      0      0   
733       2          Berriman, Mr. William John    male  23.0      0      0   
382       3                  Tikkanen, Mr. Juho    male  32.0      0      0   
704       3             Hansen, Mr. Henrik Juul    male  26.0      1      0   
813       3  Andersson, Miss. Ebba Iris Alfrida  female   6.0      4      2   

        Fare Embarked  
331  28.5000        S  
733  13.0000        S  
382   7.9250        S  
704   7.8542        S  
813  31.2750        S

In [159]:
x_train.drop(columns=['Name'],inplace=True)

In [160]:
df['Embarked'].nunique()

3

In [161]:
df.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [182]:
# applyng imputation for filling null

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.fit_transform(x_test[['Age']])
x_test_embarked = si_embarked.fit_transform(x_test[['Embarked']])


In [163]:
x_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [195]:
# One Hot coding on Sex and Embarked

ohe_sex = OneHotEncoder(handle_unknown='ignore')
ohe_embarked = OneHotEncoder(handle_unknown='ignore')

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked2 = ohe_embarked.fit_transform(x_train[['Embarked']]).toarray()

x_test_sex = ohe_sex.fit_transform(x_test[['Sex']])
x_test_embarked2 = ohe_embarked.fit_transform(x_test[['Embarked']])

In [192]:
x_train_embarked2

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], shape=(712, 4))

In [166]:
x_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [198]:
x_train_rem = x_train.drop(columns=['Age','Sex','Embarked'])
x_test_rem = x_test.drop(columns=['Age','Sex','Embarked'])

x_train_transformed = np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_embarked),axis=1)
x_test_transformed = np.concatenate((x_test_rem,x_test_age,x_test_sex,s_test_embarked),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)

In [168]:
x_train_transformed

array([[ 45.5   ,   0.    ,   1.    , ...,   0.    ,   0.    ,  28.5   ],
       [ 23.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,  13.    ],
       [ 32.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,   7.925 ],
       ...,
       [ 41.    ,   0.    ,   1.    , ...,   2.    ,   0.    ,  14.1083],
       [ 14.    ,   1.    ,   0.    , ...,   1.    ,   2.    , 120.    ],
       [ 21.    ,   0.    ,   1.    , ...,   0.    ,   1.    ,  77.2875]],
      shape=(712, 11))

In [175]:
x_test_transformed

array([[30.505845070422534, 0.0, 1.0, ..., 1, 1, 15.2458],
       [31.0, 0.0, 1.0, ..., 0, 0, 10.5],
       [20.0, 0.0, 1.0, ..., 0, 0, 7.925],
       ...,
       [38.0, 1.0, 0.0, ..., 1, 5, 31.3875],
       [17.0, 1.0, 0.0, ..., 0, 0, 10.5],
       [4.0, 1.0, 0.0, ..., 1, 1, 16.7]], shape=(179, 11), dtype=object)

In [176]:
clf = DecisionTreeClassifier()
clf.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

In [177]:
y_pred = clf.predict(x_test_transformed)
y_pred

ValueError: could not convert string to float: 'Moubarek, Master. Halim Gonios ("William George")'

In [110]:
from sklearn.metrics import accuracy_score

accuracy_score(x_test,y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [178, 712]